apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

images:
  - name: ghcr.io/ranu-ai4/bulk-email
    newName: ghcr.io/ranu-ai4/bulk-email
    newTag: "prod-placeholder"

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: bulk-emailer-web
