apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bulk-email

resources:
  - configmap.yaml
  - namespace.yaml
  - secret.yaml
  - mongodb.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
