apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bulk-email

resources:
  - ../../base

# CI automatically updates newTag on every push to dev
images:
  - name: ghcr.io/Infinia-Technology/bulk-email
    newName: ghcr.io/Infinia-Technology/bulk-email
    newTag: "dev-3238826"

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment
      name: bulk-emailer-web
